'use strict';

const DEFAULT_CONFIG = {
  size: 250,
  ticks: 100,
  seed: 'prototype-1',
  lidOpen: true,
  initialPlants: 1800,
  initialHerbivores: 180,
  initialCarnivores: 8,
  plantReproductionChance: 0.12,
  gasFluxScale: 0.003,
  gasMidpointPull: 0.08,
  rainChance: 0.11,
  rainAmount: 8,
  droughtChance: 0.04,
  droughtAmount: 3,
  evaporationOpen: 0.16,
  moistureSeepageFromWater: 1.2,
  moistureSeepageFromAdjacentWater: 0.35,
  insectDrinkAmount: 0.5,
  insectStepChargePerTick: 1.2,
  sandStepCost: 1.5,
  eggStageTicks: 4,
  larvaStageTicks: 2,
  carnivoreEggStageTicks: 2,
  carnivoreLarvaStageTicks: 1,
  herbivoreDehydrationPenalty: 0.5,
  carnivoreDehydrationPenalty: 0.2,
  herbivoreBreedEnergyMin: 14,
  herbivoreBreedEnergyCost: 6,
  herbivoreBreedCooldown: 16,
  herbivoreBreedChance: 0.2,
  carnivoreBreedEnergyMin: 18,
  carnivoreBreedEnergyCost: 7,
  carnivoreBreedCooldown: 16,
  carnivoreBreedChance: 0.18,
  herbivoreMetabolismPerTick: 0.1,
  carnivoreMetabolismPerTick: 0.05,
  carnivoreHuntRadius: 4,
  carnivoreRivalFightChance: 0.12,
  carnivoreRivalFightEnergyMin: 9,
  carnivoreRestChanceNoPrey: 0.65,
  carnivoreRestEnergyRecovery: 0.12,
  herbivoreMoveEnergyCost: 1,
  carnivoreMoveEnergyCost: 0.7,
  carnivorePreyFleeChance: 0.2,
  carnivoreAttackDamage: 2,
  carnivoreKillEnergyGain: 7,
  carnivoreApRegenPerTick: 1,
  herbivoreMaxAge: 130,
  carnivoreMaxAge: 150,
};

module.exports = {
  DEFAULT_CONFIG,
};
